### PR TITLE
Use callsite

### LINKED ISSUE #28: Use package.json To Find Package Name
https://github.com/steelbrain/package-deps/blob/26efdead33d2e447ff10f9c3b45b7e65435525df/lib/main.js#L14-L15 seems flakey and likely to fail in some circumstances. If you simply use __dirname and then walk up the tree until you find package.json, that might be a better approach?

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #28 

Thanks to @joefitzgerald for the idea!

[Review on Reviewable](https://reviewable.io/reviews/steelbrain/package-deps/29)

### CODE REVIEW

**Comment by joefitzgerald** [comment]
Those specs can only work on your computer. Suggest making them more generally runnable so others can contribute.

**Comment by steelbrain** [comment]
@joefitzgerald `apm test` is what I use to test them

**Comment by steelbrain** [comment]
Turns out `callsite` isn't cross-platform, so I wrote [sb-callsite](https://github.com/steelbrain/callsite) which uses a different v8 API and is cross-platform

File: spec/package-deps-spec.coffee [hunk 1]
```diff
@@ -88,3 +88,13 @@ describe 'Package-Deps', ->
           expect(atom.packages.activatePackage.callCount).toBe(3)
           expect(view.show.callCount).toBe(1)
           expect(view.advance.callCount).toBe(2)
+
+  describe 'helpers', ->
+
+    describe 'guessName', ->
+      Helpers = require('../lib/helpers')
```
Comment (joefitzgerald) [inline spec/package-deps-spec.coffee]: Asserting a path that includes your username is hostile to others contributing (the test will never pass for them). Use the `fixtures` directory and `temp`, and construct your target directory and files in a tempdir. Then assert against those. This will also allow you to have a single test instead of a UNIX test and a Windows test.

Comment (steelbrain) [inline spec/package-deps-spec.coffee]: I am afraid you are mistaken, `guessName` function doesn't need anything on the file system. It accepts path string and tries to guess package name from that string. The following tests are to ensure that it can extract a name from not just nix paths but from windows ones as well. The username I provided don't have to be on the file system, they are meta values and these tests should be passes for all of us (They even pass on Travis).

I hope it clarifies your concerns, if it does not, please tell me so I can explain it further :)

**Comment by steelbrain** [comment]
@joefitzgerald I believe you are a windows user, and `callsite` doesn't work on windows, it returns a simple string instead of an array of stacks (like on linux). Therefore the tests don't pass for you, but if you checkout the master of this repo, it should be working fine

**Comment by joefitzgerald** [comment]
Nope, not a Windows user. And didn't run the tests. Just saw an assertion against a specific user's path, which is bad in an integration test but ok I'm a unit test. I had assumed the former.
